{% set versions = {
  "3.4.0": "114f77b9fad95ee9fb95a5104a04e8498b65a98a",
  "3.310": "5c37f255e9957d1fe6c66124c1f28ec4a8baa672"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

{% set parts = version.split('.') | map('int') | list %}
{% set major = parts[0] %}
{% set minor = parts[1] if parts|length > 1 else 0 %}
{% set patch = parts[2] if parts|length > 2 else 0 %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "rapgap")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

build:
  number: 0
  string: "root{{ root.replace('.', '') }}"

source:
  git_url: "https://gitlab.cern.ch/jung/rapgap"
  git_rev: {{ versions.get(version, "HEAD") }}
{% if minor != 310 %}
  patches:
    - patches/cmake-cxx-standard.patch
{% endif %}

requirements:
  build:
    - root {{ root }}.*
    - {{ compiler("fortran") }}
    - gnuconfig
    - make
    - cmake<4
    - automake
    - autoconf
    - libtool

  host:
    - hepmc * root{{ root.replace('.', '') }}
    - rivet<4 root{{ root.replace('.', '') }}
    - lhapdf
    - pythia
  run:
    - hepmc * root{{ root.replace('.', '') }}
    - rivet<4 root{{ root.replace('.', '') }}
    - lhapdf
    - pythia

about:
  home: "https://rapgap.hepforge.org"
  license: "GPL-3.0"
  summary: "Hadron level Monte Carlo generator for ep and selected processes in pp scattering"
  description: |
    The Monte Carlo program RAPGAP generates a full hadron event record according to the HEP common standards. 
    In ep it can describe all inclusive and diffractive processes, in pp it is available for single-diffractive
    and a few inclusive processes for heavy quark and jet production.

extra:
  recipe-maintainers:
    - meiyasan
