{% set versions = {
  "3.302": "HEAD"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "rapgap")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

build:
  number: 0
  string: "root{{ root.replace('.', '') }}"

source:
  git_url: "https://gitlab.com/eic/mceg/RAPGAP-3.302"
  git_rev: {{ versions.get(version, "HEAD") }}

requirements:
  build:
    - root {{ root }}.*
    - {{ stdlib("c") }}
    - gnuconfig
    - make
    - automake
    - autoconf
    - libtool

  host:
    - hepmc * root{{ root.replace('.', '') }}
    - rivet<4 root{{ root.replace('.', '') }}
    - lhapdf
    - pythia
  run:
    - hepmc * root{{ root.replace('.', '') }}
    - rivet<4 root{{ root.replace('.', '') }}
    - lhapdf
    - pythia

about:
  home: "https://gitlab.com/eic/mceg/RAPGAP-3.302"
  license: "MIT"
  summary: "Hadron level Monte Carlo generator for ep and selected processes in pp scattering"
  description: |
    The Monte Carlo program RAPGAP generates a full hadron event record according to the HEP common standards. 
    In ep it can describe all inclusive and diffractive processes, in pp it is available for single-diffractive
    and a few inclusive processes for heavy quark and jet production.

extra:
  recipe-maintainers:
    - meiyasan
